### ISSUE TITLE
Post-PLDI Code Cleanup

### ISSUE THREAD

**Issue by willow-ahrens** [willow-ahrens/Finch.jl#292]
Internal:
- [x] ctx should always be the first argument #323 
- [x] all direct references to fields of the ctx should become getters/setters/etc #324 
- [ ] virtual functions should mirror lowered analogues and be approximately "pure" #325 
- [ ] SwitchVisitor and other callable visitors that are overloaded by looplets should become named functions/named looplet functions should be given uniform names #326 
- [ ] introduce abstract types with interfaces for looplets, combinators, arrays, etc and move docs and stubs there. #327 
External:
- [x] rename Fiber to Tensor #367 
- [x] https://github.com/willow-ahrens/Finch.jl/issues/226
- [x] https://github.com/willow-ahrens/Finch.jl/issues/228
- [x] merge critical continuous infrastructure to main #328

**Comment by willow-ahrens** [comment]
@nullplay Please take a look at this checklist! Let me know if you'd like to add/remove/deprioritize anything. I am treating this as the checklist for when we release the Arxiv. Sometime this weekend I will make the whole thing into a github project representing the continuous tensor release milestone.

**Comment by nullplay** [comment]
Looks good to me! I'll mainly focus on merging continuous features to main with basic insertion supports (`A[3.1415]=1`). 

I'd like to add few more things to task lists :

- [ ] Add ScaleArray array combinator (supporting stride in index expression `A[2*i]`)
- [ ] Add several continuous levels : SingleRLE(a level with single interval), SinglePinpoint
- [ ] Add continuous usage test cases from PLDI case studies
