### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by willow-ahrens** [willow-ahrens/Finch.jl#39]
#33 will make testing easier:

- [x] Test #33 thoroughly, then be sure to test:
- [ ] Dimensionalization #27
- [x] Many diff formats and kernels
- [ ] Sparse Accelerator Initialization #7
- [x] Protocols 
- [ ] Other Index Modifiers #19 #20 #21 #22 #23
- [ ] Embedding (especially error handling) #24
- [x] Pretty printing of kernels #40

**Comment by willow-ahrens** [comment]
I'm closing this as we mostly the stable parts of Finch, and we will continue to add tests as we make changes and additions to Finch.
